feat: deterministic postId
lens-protocol/lens-v3 pull request #48
Opened 2024-12-05 15:28 UTC by vicnaum

2024-12-05 15:30 UTC, vicnaum commented
Link T-23023

2024-12-05 16:56 UTC, donosonaumczuk requested changes
Conclusion: I think we should keep both sequential IDs, the "global" for the feed is super useful, like "this is the Xth post of the feed"

2024-12-05 16:56 UTC, donosonaumczuk commented on contracts/core/primitives/feed/FeedCore.sol
> +    uint256 localSequentialId; // TODO: should we accent that this is now the author-based sequential ID?
No, I think we should have both! `localSequentialId`, `authorLocalSequentialId` or similar

2024-12-05 16:56 UTC, donosonaumczuk commented on contracts/core/primitives/feed/Feed.sol
> +    function getAuthorPostId(address author, uint256 localSequentialId) external view returns (uint256) {
I think we should have the two getters, `getPostLocalSequentialId` and `getPostAuthorLocalSequentialId`

2024-12-05 16:56 UTC, donosonaumczuk commented on contracts/core/primitives/feed/FeedCore.sol
> +        return uint256(keccak256(abi.encode("evm:", block.chainid, address(this), author, localSequentialId)));
Here we could maybe use both sequential IDs, not sure. I wonder if there is any advantage for this

2024-12-05 17:34 UTC, vicnaum commented on contracts/core/primitives/feed/FeedCore.sol
> +        return uint256(keccak256(abi.encode("evm:", block.chainid, address(this), author, localSequentialId)));
We cannot, cause someone could frontrun the primitive localSequentialId

2024-12-06 10:46 UTC, donosonaumczuk commented on contracts/core/primitives/feed/FeedCore.sol
> +        return uint256(keccak256(abi.encode("evm:", block.chainid, address(this), author, localSequentialId)));
Ah true, the whole idea was to make it deterministic haha. Yeah, then this is perfect like it is

2024-12-06 11:59 UTC, donosonaumczuk requested changes

2024-12-06 11:59 UTC, donosonaumczuk commented on contracts/core/primitives/feed/Feed.sol
> +        return Core._generatePostId(author, localSequentialId);
Actually, this is wrong, this is the Post ID, not the author local sequential one

2024-12-06 12:39 UTC, donosonaumczuk commented on contracts/core/primitives/feed/FeedCore.sol
> +    uint256 localSequentialId; // TODO: should we accent that this is now the author-based sequential ID?
Added them

2024-12-06 12:39 UTC, donosonaumczuk commented on contracts/core/primitives/feed/Feed.sol
> +    function getAuthorPostId(address author, uint256 localSequentialId) external view returns (uint256) {
Added both of them

2024-12-06 12:40 UTC, donosonaumczuk commented on contracts/core/primitives/feed/Feed.sol
> +        return Core._generatePostId(author, localSequentialId);
Not sure what this getter was

2024-12-06 13:07 UTC, merged